import { PackageData } from '../types';
import { generateUniqueId } from '../utils/formatters';

export function getEmptyPackage(): PackageData {
  const id = generateUniqueId('pkg');
  const now = new Date().toISOString();
  return {
    id,
    packageDetails: {
      id,
      packageName: 'New Domestic Tour Package',
      destination: '',
      travelDate: new Date().toISOString().split('T')[0],
      days: 4,
      nights: 3,
      createdAt: now,
      updatedAt: now,
    },
    pax: {
      adults: 2,
      children: 0,
      infants: 0,
      childPercentage: 70,
      infantPercentage: 0,
    },
    roomAllocation: {
      doubleRooms: 1,
      tripleRooms: 0,
      quadRooms: 0,
    },
    hotels: [
      {
        id: generateUniqueId('hotel'),
        destination: '',
        hotelName: '',
        roomCategory: 'Deluxe Room',
        mealPlan: 'CP',
        nights: 3,
        doubleRate: 3500,
        extraBedRate: 1200,
        supplier: '',
        notes: '',
        selectedOptionId: 'opt_1',
        options: [
          {
            id: 'opt_1',
            hotelName: '',
            roomCategory: 'Deluxe Room',
            mealPlan: 'CP',
            doubleRate: 3500,
            extraBedRate: 1200,
            supplier: '',
            notes: '',
          },
        ],
      },
    ],
    vehicles: [
      {
        id: generateUniqueId('veh'),
        vehicleType: 'Sedan',
        vehicleName: 'AC Dzire / Etios',
        numberOfVehicles: 1,
        numberOfDays: 4,
        ratePerDay: 2800,
        costingBasis: 'per_day',
      },
    ],
    meals: [],
    activities: [],
    flightTrainFares: [],
    otherServices: [],
    pricingSettings: {
      markupType: 'percentage',
      markupValue: 15,
      rounding: '500',
    },
  };
}

export function getRajasthanDemoPackage(): PackageData {
  const id = generateUniqueId('pkg_demo');
  const now = new Date().toISOString();

  return {
    id,
    packageDetails: {
      id,
      packageName: 'Rajasthan Family Tour',
      destination: 'Rajasthan (Udaipur - Jodhpur - Jaipur)',
      travelDate: '2026-11-15',
      days: 6,
      nights: 5,
      createdAt: now,
      updatedAt: now,
    },
    pax: {
      adults: 4,
      children: 2,
      infants: 0,
      childPercentage: 70,
      infantPercentage: 0,
    },
    roomAllocation: {
      doubleRooms: 1,
      tripleRooms: 1,
      quadRooms: 0,
    },
    hotels: [
      {
        id: generateUniqueId('hotel_udr'),
        destination: 'Udaipur',
        hotelName: 'Radisson Blu Resort & Spa',
        roomCategory: 'Deluxe Lake View',
        mealPlan: 'CP',
        nights: 2,
        doubleRate: 4000,
        extraBedRate: 1500,
        supplier: 'Rajasthan Royal DMCs',
        notes: 'Includes buffet breakfast and welcome drinks',
        selectedOptionId: 'opt_udr_1',
        options: [
          {
            id: 'opt_udr_1',
            hotelName: 'Radisson Blu Resort & Spa',
            roomCategory: 'Deluxe Lake View',
            mealPlan: 'CP',
            doubleRate: 4000,
            extraBedRate: 1500,
            supplier: 'Rajasthan Royal DMCs',
            notes: '4-Star Lake view property with breakfast',
          },
          {
            id: 'opt_udr_2',
            hotelName: 'Heritage Haveli on Lake Pichola',
            roomCategory: 'Heritage Standard',
            mealPlan: 'CP',
            doubleRate: 2800,
            extraBedRate: 1000,
            supplier: 'Mewar Heritage Stays',
            notes: 'Budget heritage property near City Palace',
          },
          {
            id: 'opt_udr_3',
            hotelName: 'Taj Lake Palace / The Oberoi Udaivilas',
            roomCategory: 'Luxury Palace Room',
            mealPlan: 'CP',
            doubleRate: 14000,
            extraBedRate: 3500,
            supplier: 'Luxury DMCs India',
            notes: '5-Star Luxury VIP Experience',
          },
        ],
      },
      {
        id: generateUniqueId('hotel_jdh'),
        destination: 'Jodhpur',
        hotelName: 'Ajit Bhawan Palace Resort',
        roomCategory: 'Executive Heritage Room',
        mealPlan: 'CP',
        nights: 1,
        doubleRate: 3500,
        extraBedRate: 1200,
        supplier: 'Marwar Holiday Link',
        notes: 'Heritage property stay',
        selectedOptionId: 'opt_jdh_1',
        options: [
          {
            id: 'opt_jdh_1',
            hotelName: 'Ajit Bhawan Palace Resort',
            roomCategory: 'Executive Heritage Room',
            mealPlan: 'CP',
            doubleRate: 3500,
            extraBedRate: 1200,
            supplier: 'Marwar Holiday Link',
            notes: 'Heritage resort stay',
          },
          {
            id: 'opt_jdh_2',
            hotelName: 'Indana Palace Jodhpur',
            roomCategory: 'Premium Room',
            mealPlan: 'MAP',
            doubleRate: 4500,
            extraBedRate: 1500,
            supplier: 'Jodhpur DMC',
            notes: 'Includes breakfast & royal dinner',
          },
        ],
      },
      {
        id: generateUniqueId('hotel_jpr'),
        destination: 'Jaipur',
        hotelName: 'ITC Rajputana / The Lalit',
        roomCategory: 'Premium Family Suite',
        mealPlan: 'MAP',
        nights: 2,
        doubleRate: 4500,
        extraBedRate: 1500,
        supplier: 'Pink City Holidays',
        notes: 'Breakfast & Dinner included',
        selectedOptionId: 'opt_jpr_1',
        options: [
          {
            id: 'opt_jpr_1',
            hotelName: 'ITC Rajputana / The Lalit',
            roomCategory: 'Premium Family Suite',
            mealPlan: 'MAP',
            doubleRate: 4500,
            extraBedRate: 1500,
            supplier: 'Pink City Holidays',
            notes: '5-Star Hotel with Breakfast & Dinner included',
          },
          {
            id: 'opt_jpr_2',
            hotelName: 'The Fern Residency Jaipur',
            roomCategory: 'Winter Green Room',
            mealPlan: 'CP',
            doubleRate: 2600,
            extraBedRate: 900,
            supplier: 'Jaipur Hotel Hub',
            notes: 'Eco-friendly 3-star business hotel',
          },
        ],
      },
    ],
    vehicles: [
      {
        id: generateUniqueId('veh_innova'),
        vehicleType: 'Innova Crysta',
        vehicleName: 'Toyota Innova Crysta (6+1 AC)',
        numberOfVehicles: 1,
        numberOfDays: 6,
        ratePerDay: 4500,
        costingBasis: 'per_day',
      },
    ],
    meals: [
      {
        id: generateUniqueId('meal_bk'),
        mealName: 'Daily Buffet Breakfast (En-route)',
        mealType: 'Breakfast',
        numberOfMeals: 5,
        adultRate: 350,
        childRate: null,
        infantRate: 0,
      },
      {
        id: generateUniqueId('meal_dn'),
        mealName: 'Traditional Rajasthani Thali Dinner',
        mealType: 'Special Dinner',
        numberOfMeals: 3,
        adultRate: 650,
        childRate: 450,
        infantRate: 0,
      },
    ],
    activities: [
      {
        id: generateUniqueId('act_cp'),
        activityName: 'City Palace & Crystal Gallery Entry',
        destination: 'Udaipur',
        adultRate: 500,
        childRate: 300,
        infantRate: 0,
        adultQuantity: 4,
        childQuantity: 2,
        infantQuantity: 0,
      },
      {
        id: generateUniqueId('act_boat'),
        activityName: 'Private Boat Cruise on Lake Pichola',
        destination: 'Udaipur',
        adultRate: 450,
        childRate: null,
        infantRate: 0,
        adultQuantity: 4,
        childQuantity: 2,
        infantQuantity: 0,
      },
      {
        id: generateUniqueId('act_amber'),
        activityName: 'Amber Fort Elephant / Jeep Ride',
        destination: 'Jaipur',
        adultRate: 600,
        childRate: 350,
        infantRate: 0,
        adultQuantity: 4,
        childQuantity: 2,
        infantQuantity: 0,
      },
      {
        id: generateUniqueId('act_desert'),
        activityName: 'Desert Safari & Folk Dance Show',
        destination: 'Jodhpur',
        adultRate: 1200,
        childRate: 800,
        infantRate: 0,
        adultQuantity: 4,
        childQuantity: 2,
        infantQuantity: 0,
      },
    ],
    flightTrainFares: [
      {
        id: generateUniqueId('fare_air1'),
        transportType: 'Flight',
        sector: 'Delhi (DEL) -> Udaipur (UDR)',
        flightOrTrainNumber: '6E-2041 Indigo',
        adultRate: 4200,
        childRate: 4200,
        infantRate: 1500,
        adultQuantity: 4,
        childQuantity: 2,
        infantQuantity: 0,
        notes: 'Includes 15kg check-in baggage',
      },
      {
        id: generateUniqueId('fare_air2'),
        transportType: 'Flight',
        sector: 'Jaipur (JAI) -> Delhi (DEL)',
        flightOrTrainNumber: 'AI-492 Air India',
        adultRate: 3500,
        childRate: 3500,
        infantRate: 1200,
        adultQuantity: 4,
        childQuantity: 2,
        infantQuantity: 0,
        notes: 'Return flight sector',
      },
    ],
    otherServices: [
      {
        id: generateUniqueId('os_ins'),
        serviceName: 'Comprehensive Domestic Travel & Medical Insurance',
        quantity: 6,
        rate: 250,
        notes: 'Covers all 6 passengers for 6 days',
      },
      {
        id: generateUniqueId('os_wel'),
        serviceName: 'Traditional Royal Welcome (Garland, Tikka & Welcome Drink)',
        quantity: 6,
        rate: 150,
        notes: 'At Udaipur arrival hotel',
      },
    ],
    pricingSettings: {
      markupType: 'percentage',
      markupValue: 15,
      rounding: '500',
    },
  };
}
